# --- deps ---
FROM node:20-alpine AS deps
WORKDIR /app
# Sharp & friends on Alpine
RUN apk add --no-cache libc6-compat
# Install prod deps strictly from lockfile
COPY package.json package-lock.json ./
RUN npm ci

# --- builder ---
FROM node:20-alpine AS builder
WORKDIR /app
ENV NODE_ENV=production
RUN apk add --no-cache libc6-compat
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Build-time public envs (only NEXT_PUBLIC_* should go here)
ARG NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
RUN npm run build

# --- runner ---
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN apk add --no-cache libc6-compat

# Copy minimal standalone server produced by Next.js
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Optional: run as non-root
USER node

EXPOSE 3000
# server.js is generated by output: 'standalone'
CMD ["node", "server.js"]
